<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>

  <body>
    <script>
      function testAwait() {
        console.log("object");
        return new Promise((resolve) => {
          setTimeout(function () {
            console.log("testAwait");
            resolve();
          }, 1000);
        });
      }

      async function helloAsync() {
        await testAwait();
        console.log("helloAsync");
      }
      helloAsync();
      // object
      // testAwait
      // helloAsync

      async function async1() {
        console.log("AAAA");
        async2();
        console.log("BBBB");
      }
      async function async2() {
        console.log("CCCC");
      }

      console.log("DDDD");
      setTimeout(function () {
        console.log("FFFF");
      }, 0);
      async1();
      new Promise(function (resolve) {
        console.log("GGGG");
        resolve();
      }).then(function () {
        console.log("HHHH");
      });
      console.log("IIII");
      // DDDD AAAA CCCC BBBB GGGG IIII HHHH FFFF

      {
        async function async1() {
          console.log("AAAA");
          await async2(); //  await new Promise(function(resolve) { resulve(undefined) })
          console.log("BBBB");
        }
        async function async2() {
          console.log("CCCC");
        }

        console.log("DDDD");
        setTimeout(function () {
          console.log("FFFF");
        }, 0);
        async1();
        new Promise(function (resolve) {
          console.log("GGGG");
          resolve();
        }).then(function () {
          console.log("HHHH");
        });
        console.log("IIII");
        // DDDD AAAA GGGG IIII CCCC BBBB
      }

      (function () {
        console.clear();
        // async异步函数始终返回Promise
        async function foo() {
          console.log(1);
          // return Promise.reject(2); // catch捕获
          // Promise.resolve(2);
          // return await 1000
          // throw "errrrr"; // catch捕获
          return new Promise((res, rej) => {
            setTimeout(Math.random() * 10 > 5 ? res : rej, 2000);
          });
        }
        foo().then(console.log).catch(console.warn); // async函数返回值会被Promise.resolve包裹
      })();
    </script>
  </body>
</html>
